on: [push]

name: build for windows

jobs:
  build_and_test:
    name: build rust for release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features
      - run: tree /F
          
      - uses: actions/upload-artifact@v2
        with:
          name: ubuntu_release_file
          path: D:\a\how_many_lines\how_many_lines
